export const ACTIONS = {
  SET_CLIENTS: 'SET_CLIENTS',
  SET_PROSPECTS: 'SET_PROSPECTS',
  SET_VISIBLE_PROSPECTS: 'SET_VISIBLE_PROSPECTS',
  SET_POLYGON: 'SET_POLYGON',

  SET_SELECTED_CLIENT: 'SET_SELECTED_CLIENT',

  SET_SELECTED_PROSPECT: 'SET_SELECTED_PROSPECT',

  SET_SHOW_EXAMPLES_MENU: 'SET_SHOW_EXAMPLES_MENU',

  SET_MODE: 'SET_MODE',

  CLEAR_MAP: 'CLEAR_MAP',
};
